feat: homePage 1차 완성
FRONTENDSCHOOL10/Haemadi pull request #86
Opened 2024-09-16 08:12 UTC by joowon-jang

## PR 유형

- [x] Feat: 새로운 기능 추가
- [ ] BugFix: 버그 수정
- [ ] Design: CSS 등 사용자 UI 디자인 변경
- [ ] Style: 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [x] Refactor: 코드 리팩토링
- [ ] Comment: 주석 추가 및 수정
- [ ] Docs: 문서 수정
- [ ] Test: 테스트 추가, 테스트 리팩토링
- [ ] Chore: 빌드 부분 혹은 패키지 매니저 수정
- [ ] Rename: 파일 혹은 폴더명 수정
- [ ] Remove: 파일 혹은 폴더 삭제

## 🔧 반영 브랜치
feature/HomePage -> develop

## 💬 Description
- 로그인 기능 구현 완료되면 유리병 버튼 위 쪽의 메세지 렌더링 여부 추가하겠습니다
- 레이아웃과 배경이미지 등 디자인 관련 부분은 완성입니다
- PlusButton 컴포넌트의 중단점을 homePage(예외적으로 1024px)와 동일하게 하기 위해 props로 desktop을 전달받도록 변경
- BottleLink 컴포넌트를 조건에 따라 페이지 이동가능 여부가 결정되기 때문에 Link -> button으로 변경 (useNavigate 사용)
- sunStore 저장소에서 sunset(18시~6시 사이인지) 상태를 관리하고 homePage로 들어갈 때마다 sunset여부 변경하도록 하며, homePage의 배경 이미지를 sunset 상태에 따라 변경
- 화면을 페이지 바깥까지 스크롤 하려고 하면 오버스크롤(바운싱) 현상이 있어서 _base.css에 overscroll-behavior: none 추가
- PlusButton 클릭 시 열리는 감정 선택 Modal창 제작 (Focus Trapping 완료, 열렸을 때 바깥쪽 스크롤 방지 완료)
- Greeting 컴포넌트 제작 (홈 화면 위 쪽의 인사문구 메세지 및 버튼)
- router에서 write-diary 경로에 emotion params추가 (homePage에서 감정 선택 시 해당 감정을 일기 작성 페이지로 전달하기 위함)

## 📷 Screenshots
<img width="365" alt="스크린샷 2024-09-16 오후 5 11 19" src="https://github.com/user-attachments/assets/8e60f1dd-a90b-42a3-b852-826aa017beb7">
<img width="576" alt="스크린샷 2024-09-16 오후 5 11 38" src="https://github.com/user-attachments/assets/262f9201-b858-4356-adf6-0b4e449f6b74">
<img width="1680" alt="스크린샷 2024-09-16 오후 5 11 55" src="https://github.com/user-attachments/assets/7cda08be-1a9a-4cf0-86c7-be17559a491d">
<img width="365" alt="스크린샷 2024-09-16 오후 5 12 20" src="https://github.com/user-attachments/assets/2d69f5bf-807e-41ed-9a83-6e0b3c4cc590">
<img width="1680" alt="스크린샷 2024-09-16 오후 5 12 38" src="https://github.com/user-attachments/assets/cf49670e-f5e4-40e6-8295-e90a37eb8d6b">

Resolves #81

2024-09-19 17:34 UTC, jaehwan-space reviewed
행복해요, 기뻐요 조개 호버 시 두개의 이미지가 서로 바뀐 것 같습니다!

2024-09-19 18:16 UTC, jaehwan-space requested changes
![image](https://github.com/user-attachments/assets/27c34da8-2934-4fb5-aeb5-caf1305576a9)

가로가 2000px 이상 넘어가면 조개의 가운데 정렬이 망가집니다..!

2024-09-20 00:28 UTC, jaehwan-space approved these changes
수고하셨습니다 👍

2024-09-20 05:21 UTC, siyo0723 approved these changes
수고하셨습니다!

2024-09-20 05:52 UTC, merged